# Generated by Django 4.1 on 2022-08-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chanson',
            name='titre',
            field=models.CharField(max_length=30),
        ),
    ]
