# Generated by Django 4.1 on 2022-08-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0003_artiste_en_activite_alter_chanson_artiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='en_activite',
        ),
    ]
