# Generated by Django 4.1.2 on 2022-11-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0004_remove_artiste_en_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='UNDEFINED', max_length=50)),
                ('prenom', models.CharField(default='UNDEFINED', max_length=50)),
                ('dateNaissance', models.DateField()),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=300)),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame')], default='UNDEFINED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='UNDEFINED', max_length=50)),
                ('prenom', models.CharField(default='UNDEFINED', max_length=50)),
                ('dateNaissance', models.DateField()),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=300)),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame')], default='UNDEFINED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp1.conducteur')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroen'), ('VOLKSWAGEN', 'Volkswagen'), ('MERCEDES', 'Mercedes'), ('BMW', 'BMW'), ('AUDI', 'Audi'), ('FIAT', 'Fiat'), ('OPEL', 'Opel'), ('TOYOTA', 'Toyota'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('SUZUKI', 'Suzuki'), ('HONDA', 'Honda'), ('MAZDA', 'Mazda'), ('SUBARU', 'Subaru'), ('LAND ROVER', 'Land Rover'), ('JEEP', 'Jeep'), ('FORD', 'Ford'), ('CHEVROLET', 'Chevrolet'), ('DODGE', 'Dodge'), ('VOLVO', 'Volvo'), ('SEAT', 'Seat'), ('SKODA', 'Skoda'), ('ALFA ROMEO', 'Alfa Romeo'), ('MASERATI', 'Maserati'), ('LAMBORGHINI', 'Lamborghini'), ('FERRARI', 'Ferrari'), ('PORSCHE', 'Porsche'), ('ASTON MARTIN', 'Aston Martin'), ('BENTLEY', 'Bentley'), ('JAGUAR', 'Jaguar'), ('MINI', 'Mini'), ('SMART', 'Smart'), ('DS', 'DS')], default='UNDEFINED', max_length=50)),
                ('modele', models.CharField(default='UNDEFINED', max_length=50)),
                ('kilometrage', models.IntegerField(default=0)),
                ('prixjournalier', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('NONDISPONIBLE', 'Non disponible')], default='DISPONIBLE', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='chanson',
            name='artiste',
        ),
        migrations.DeleteModel(
            name='Artiste',
        ),
        migrations.DeleteModel(
            name='Chanson',
        ),
        migrations.AddField(
            model_name='location',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp1.vehicule'),
        ),
    ]
