# Generated by Django 4.1.2 on 2022-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0005_administrateur_conducteur_location_vehicule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
