# Generated by Django 4.1.2 on 2022-11-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0006_administrateur_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
