# Generated by Django 4.1.2 on 2022-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0009_location_kilometragedepart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=50),
        ),
    ]
